export default [
  {
    id: 1,
    expectedTime: ["30/09/2023", "15/10/2023"],
    route: ["Sài Gòn", "Sapa"],
    numAdult: 2,
    nameA: ["Lê Thị Bích Hằng", "Nguyễn Văn A"],
    numChild: 2,
    nameC: ["Nguyễn Văn B", "Nguyễn Văn C"],
    tourStatus: "Waiting for handling",
  },
  {
    id: 2,
    expectedTime: ["30/09/2023", "15/10/2023"],
    route: ["Sài Gòn", "Sapa"],
    numAdult: 2,
    nameA: ["Lê Thị Bích Hằng", "Nguyễn Văn A"],
    numChild: 2,
    nameC: ["Nguyễn Văn B", "Nguyễn Văn C"],
    tourStatus: "Waiting for handling",
  },
  {
    id: 3,
    expectedTime: ["30/09/2023", "15/10/2023"],
    route: ["Sài Gòn", "Sapa"],
    numAdult: 2,
    nameA: ["Lê Thị Bích Hằng", "Nguyễn Văn A"],
    numChild: 2,
    nameC: ["Nguyễn Văn B", "Nguyễn Văn C"],
    tourStatus: "Waiting for handling",
  },
];
