export default [
    {
      id: 1,
      expectedTime:['30/09/2023', '15/10/2023'],
      route: ['Sài Gòn', 'Sapa'],
      numAdult: 2,
      nameA: ['Lê Thị Bích Hằng', 'Nguyễn Văn A'],
      numChild: 2,
      nameC: ['Nguyễn Văn B', 'Nguyễn Văn C'],
      tourStatus: 'WaitingForHandling',
      bookingID: '1234',
      bookingDate: '01/09/2023',
    },
    {
        id: 2,
        expectedTime:['30/09/2023', '15/10/2023'],
        route: ['Sài Gòn', 'Sapa'],
        numAdult: 2,
        nameA: ['Lê Thị Bích Hằng', 'Nguyễn Văn A'],
        numChild: 2,
        nameC: ['Nguyễn Văn B', 'Nguyễn Văn C'],
        tourStatus: 'Confirmed',
        bookingID: '1234',
        bookingDate: '01/09/2023',
      },
      {
        id: 3,
        expectedTime:['30/09/2023', '15/10/2023'],
        route: ['Sài Gòn', 'Sapa'],
        numAdult: 2,
        nameA: ['Lê Thị Bích Hằng', 'Nguyễn Văn A'],
        numChild: 2,
        nameC: ['Nguyễn Văn B', 'Nguyễn Văn C'],
        tourStatus: 'Paid',
        bookingID: '1234',
        bookingDate: '01/09/2023',
      },
  ]